name: Build and Push Docker Image

on:
  push:
    branches:
      - prod
  pull_request:
    branches:
      - prod

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PATH }}" | docker login docker.io -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and Push Image
        run: |
          IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/infrawatch-backend:latest
          docker build -t $IMAGE .
          docker push $IMAGE
          docker logout

      - name: Initialize Conteiner on VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{secrets.VPS_HOST}}
          username: ${{secrets.VPS_USER}}
          key: ${{secrets.VPS_KEY}}
          script: |
            IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/infrawatch-backend:latest
            docker stop backend || true
            docker rm backend || true
            docker pull $IMAGE
            docker run -d --name backend --restart=always $IMAGE
